version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: kucing-store_mongodb
    restart: always
    expose:
      - '27017'
    networks:
      - kucing-store-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: kucing-store_mongo-express
    restart: always
    networks:
      - kucing-store-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  kucing-store:
    image: kucing_store_image
    container_name: kucing-store-nextjs
    restart: always
    networks:
      - kucing-store-network
    ports:
      - 3000:3000
    env_file:
      - ../.env
    depends_on:
      - mongo

networks:
  kucing-store-network:
    driver: bridge
